version: "3"

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - /sessions
    ports:
      - 8080:80
